version: "3.8"

services:
  api-min:
    profiles: ['prod']
    ports:
      - "8080:8080"
    image: ghcr.io/holmes89/hello-api:min
    build: .

  api-dev:
    profiles: ['dev']
    ports:
      - "8080:8080"
    image: ghcr.io/holmes89/hello-api:dev
    build:
      context: .
      target: dev

