services:
  api-min:
    profiles: ["prod"]
    ports:
      - "8080:8080"
    image: ghcr.io/kazakh-in-nz/hello-api:min
    build: .

  api-dev:
    profiles: ["dev"]
    ports:
      - "8080:8080"
    image: ghcr.io/kazakh-in-nz/hello-api:dev
    build:
      context: .
      target: dev

  database:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/:/data/
